# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd/squirrel
    id: squirrel
    binary: squirrel
    ldflags:
      - -X github.com/omarahm3/squirrel/client.domain={{ .Env.DOMAIN }}
      - -X github.com/omarahm3/squirrel/client.loglevel={{ .Env.LOG_LEVEL }}
      - -X github.com/omarahm3/squirrel/client.env={{ .Env.APP_ENV }}
      - -s
      - -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - main: ./cmd/squirreld
    id: squirreld
    binary: squirreld
    ldflags:
      - -X github.com/omarahm3/squirrel/server.domain={{ .Env.DOMAIN }}
      - -X github.com/omarahm3/squirrel/server.loglevel={{ .Env.LOG_LEVEL }}
      - -X github.com/omarahm3/squirrel/server.env={{ .Env.APP_ENV }}
      - -X github.com/omarahm3/squirrel/server.port={{ .Env.PORT }}
      - -X github.com/omarahm3/squirrel/server.readBufferSize={{ .Env.READ_BUFFER_SIZE }}
      - -X github.com/omarahm3/squirrel/server.writeBufferSize={{ .Env.WRITE_BUFFER_SIZE }}
      - -s
      - -w
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - id: squirreld
    ids:
      - squirreld
    goos: linux
    goarch: amd64
    image_templates:
      - "omarahm3/squirreld:latest"
      - "omarahm3/squirreld:{{ .Tag }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/omarahm3/squirrel
      - --label=org.opencontainers.image.source=https://github.com/omarahm3/squirrel
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
archives:
  - id: squirrel
    builds:
      - squirrel
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
nfpms:
  - id: squirrel
    maintainer: omarahm3 <me@mrg.sh>
    description: Realtime logs sharing by piping squirrel to stdout
    homepage: https://github.com/omarahm3/squirrel
    license: MIT
    package_name: squirrel
    builds:
      - squirrel
    formats:
      - deb
      - rpm
      - apk
  - id: squirreld
    maintainer: omarahm3 <me@mrg.sh>
    description: Squirreld is squirrel server meant to handle sharing logs between broadcaster and subscriber
    homepage: https://github.com/omarahm3/squirrel
    license: MIT
    package_name: squirreld
    builds:
      - squirreld
    formats:
      - deb
      - rpm
      - apk
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
