# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./main/squirrel
    id: squirrel
    binary: squirrel
    env:
      - CGO_ENABLED=0
      - LOG_LEVEL=error
      - APP_ENV=prod
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - main: ./main/squirreld
    id: squirreld
    binary: squirreld
    env:
      - CGO_ENABLED=0
      - LOG_LEVEL=debug
      - APP_ENV=dev
      - PORT=8080
    goos:
      - linux
    goarch:
      - amd64
archives:
  - id: squirrel
    builds:
      - squirrel
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
